[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[dev]
  command = "npm run start"
  port = 8000        # Changed from 8888
  targetPort = 3000  # Your React app port
  publish = "build"
  functionsPort = 9999  # Port for Netlify Functions
