[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"

[functions]
  node_bundler = "esbuild"

[dev]
  targetPort = 3000
  port = 8888

# Development URLs configuration
[[redirects]]
  from = "http://localhost:3000/*"
  to = "/.netlify/identity/:splat"
  status = 200

[[redirects]]
  from = "http://127.0.0.1:3000/*"
  to = "/.netlify/identity/:splat"
  status = 200

[[headers]]
  for = "http://localhost:3000/*"
    [headers.values]
    Access-Control-Allow-Origin = "http://localhost:3000"

[[headers]]
  for = "http://127.0.0.1:3000/*"
    [headers.values]
    Access-Control-Allow-Origin = "http://127.0.0.1:3000"
