[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

# Disable asset optimization since Create React App already handles this
[build.processing]
  skip_processing = true

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = false

# Add this new Identity specific redirect
[[redirects]]
  from = "/.netlify/identity/*"
  to = "/.netlify/identity/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"

[functions]
  node_bundler = "esbuild"

[dev]
  targetPort = 3012
  port = 8888
  publish = "public"
  functionsPort = 8887

[[redirects]]
  from = "/.netlify/identity/*"
  to = "/.netlify/identity/:splat"
  status = 200
  force = true

# Development URLs configuration
[[redirects]]
  from = "http://localhost:3012/*"
  to = "/.netlify/identity/:splat"
  status = 200
  force = true

[[redirects]]
  from = "http://127.0.0.1:3012/*"
  to = "/.netlify/identity/:splat"
  status = 200
  force = true

[[headers]]
  for = "http://localhost:3012/*"
    [headers.values]
    Access-Control-Allow-Origin = "http://localhost:3012"

[[headers]]
  for = "http://127.0.0.1:3012/*"
    [headers.values]
    Access-Control-Allow-Origin = "http://127.0.0.1:3012"
